name: Gradle Master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['1.8']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: spring-security-core:check
        run: ./gradlew -Dgeb.env=chromeHeadless :spring-security-core:check --console=plain
      - name: spring-security-core:install
        run: ./gradlew :spring-security-core:install --console=plain
      - name: integration-test-app:check
        run: ./gradlew -Dgeb.env=chromeHeadless :integration-test-app:check --console=plain
